title: Blood Moon's Gaze
description: Fantasy RPG Wiki for bronze and sorcery gaming.
remote_theme: just-the-docs

url: https://jumajuicetime.github.io/Blood-Moon-s-Gaze/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
